### ISSUE TITLE
Here is the chart?

### ISSUE THREAD

**Issue by adamjonas** [learn-co-curriculum/instant-datascience#2]
![screen shot 2018-03-15 at 3 24 43 pm](https://user-images.githubusercontent.com/755825/37486543-2b160858-2865-11e8-8789-1affdb2a988f.png)

Not seeing the chart.

**Comment by aturkewi** [comment]
Same for me. I don't see the chart on Learn, but I do see if when I view the lesson on github...

<img width="1048" alt="screen shot 2018-03-18 at 12 52 32 pm" src="https://user-images.githubusercontent.com/13033515/37568420-3c6bc820-2aab-11e8-8334-f29554f75eb8.png">

**Comment by aturkewi** [comment]
Tried fixing by adding alt text and that just caused broken images to show up rather than the correct images. I think the issue may be Learn loading images from inside the repo? I believe we have docs saying to post images on S3 instead: https://github.com/learn-co-curriculum/instant-datascience/pull/4

cc @JeffKatzy

**Comment by aturkewi** [comment]
Also, `index-cards.png` doe not exist in this repo

**Comment by JeffKatzy** [comment]
right - ok will have to make this fix with all images.

**Comment by tkoar** [comment]
Added assets to s3 and added links to index and updated readme
